### PR TITLE
Avoid export all

### PR DESCRIPTION
**Pull request by kbaird**

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
HA! @gadgetci can't compile this because …
```erlang
compile: warnings being treated as errors
src/export_all.erl:3: export_all flag enabled - all functions will be exported
make:
*** [ebin/erlang_standards.app] Error 1
```

I will fix it.

**Comment by elbrujohalcon** [comment]
@kbaird it should be fixed now, can you rebase/merge please?

**Comment by kbaird** [comment]
I am not offered the merge button, presumably due to permissions.

**Comment by elbrujohalcon** [comment]
@kbaird I meant: can you merge `master` *into* your branch and then push?

**Comment by kbaird** [comment]
Done. Thanks for the fix.

**Pull request merged**
